# Generated by Django 2.2.4 on 2020-10-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['catagory']},
        ),
    ]
