# Generated by Django 2.2.4 on 2020-10-12 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20201009_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislike',
            field=models.ManyToManyField(blank=True, default=None, related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='dislike_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
