# Generated by Django 2.2.4 on 2020-10-14 14:57

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201012_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default_profile_image4.jpg', null=True, upload_to='catagory_avatar/%Y/%m/%d/'),
        ),
    ]
