# Generated by Django 2.2.4 on 2020-10-14 16:35

from django.conf import settings
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20201012_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default_cover_image4.jpg', null=True, upload_to='catagory_avatar/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='catagory',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
