# Generated by Django 2.2.4 on 2020-10-14 16:28

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_catagory_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default_cover_image4.jpg', null=True, upload_to='catagory_avatar/%Y/%m/%d/'),
        ),
    ]
