# Generated by Django 2.2.4 on 2020-10-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201014_2235'),
        ('core', '0006_auto_20201014_2228'),
    ]

    operations = [
    ]
