# Generated by Django 2.2.4 on 2020-10-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201014_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='avatar',
        ),
    ]
