# Generated by Django 2.2.4 on 2020-10-12 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0002_comment_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dislike_count',
            new_name='downvote_count',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='like_count',
            new_name='upvote_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.AddField(
            model_name='comment',
            name='downvote',
            field=models.ManyToManyField(blank=True, default=None, related_name='downvoter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvote',
            field=models.ManyToManyField(blank=True, default=None, related_name='upvoter', to=settings.AUTH_USER_MODEL),
        ),
    ]
